name: 'Hello World'
description: 'Run swift command.'
inputs:
  swift-subcommand:
    description: 'Swift subcommand to run'
    required: true
    default: '--version'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.swift-subcommand }}
