on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    container:
      image: swift:5.9
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Swift Version
        run: swift --version
      - name: Swift Build
        run: swift build
      - name: Swift Test
        run: swift test
      - name: Swift Run
        run: swift run
